version: '3.3'

services:
  bot:
    image: carrier_bot_image
    container_name: carrier_bot
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
    - .:/usr/src/app/bot
    command: python3 bot.py 
    restart: always
    env_file:
      - ".env"
    networks:
    - tg_bot
  web:
    image: carrier_web_image
    container_name: carrier_web
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
    - .:/usr/src/app/bot
    command: python3 django_manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - ".env"
    networks:
    - tg_bot
  db:
    container_name: db_carrier_bot
    hostname: $DB_HOST
    image: postgres:12.2

    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    restart: always
    networks:
      - tg_bot
    env_file:
      - ".env"
    volumes:
      - ./postgres:/var/lib/postgresql

  redis:
    image: 'bitnami/redis:latest'
    hostname: $REDIS_HOST
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=$REDIS_PORT
    env_file:
      - ".env"
    networks:
      - tg_bot

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - tg_bot
    

networks:
  tg_bot:
    driver: bridge
