# Generated by Django 4.1.1 on 2022-11-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_remove_bustranslation_bus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TownTranslations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('translation', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.town')),
            ],
            options={
                'verbose_name': 'Town Translation',
                'verbose_name_plural': 'Town Translations',
                'db_table': 'towns_translations',
            },
        ),
        migrations.CreateModel(
            name='TicketTypeTranslations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('translation', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tickettype')),
            ],
            options={
                'verbose_name': 'Ticket Type Translation',
                'verbose_name_plural': 'Ticket Type Translations',
                'db_table': 'ticket_type_translations',
            },
        ),
        migrations.CreateModel(
            name='StationTranslations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('translation', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.station')),
            ],
            options={
                'verbose_name': 'Station Translation',
                'verbose_name_plural': 'Station Translations',
                'db_table': 'stations_translations',
            },
        ),
        migrations.CreateModel(
            name='BusTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description_translation', models.TextField()),
                ('name_translation', models.CharField(max_length=255)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bus')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
            options={
                'verbose_name': 'Bus Translation',
                'verbose_name_plural': 'Bus Translations',
                'db_table': 'bus_translations',
            },
        ),
        migrations.CreateModel(
            name='BusOptionTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('translation', models.CharField(max_length=255)),
                ('bus_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.busoption')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
            options={
                'verbose_name': 'Bus Option Translation',
                'verbose_name_plural': 'Bus Option Translations',
                'db_table': 'bus_option_translations',
            },
        ),
    ]
